// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package contacts

import ()

type People struct {
	ID         int64  `db:"id" json:"id"`
	Name       string `db:"name" json:"name"`
	Pic        string `db:"pic" json:"pic"`
	Groups     string `db:"groups" json:"groups"`
	Emails     string `db:"emails" json:"emails"`
	Phones     string `db:"phones" json:"phones"`
	SocialNets string `db:"social_nets" json:"social_nets"`
	Wallets    string `db:"wallets" json:"wallets"`
	Locations  string `db:"locations" json:"locations"`
	Events     string `db:"events" json:"events"`
	Notes      string `db:"notes" json:"notes"`
}
