// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package contacts

import (
	"database/sql"
)

type People struct {
	ID         int64          `db:"id" json:"id"`
	Name       string         `db:"name" json:"name"`
	Pic        sql.NullString `db:"pic" json:"pic"`
	Groups     sql.NullString `db:"groups" json:"groups"`
	Emails     sql.NullString `db:"emails" json:"emails"`
	Phones     sql.NullString `db:"phones" json:"phones"`
	SocialNets sql.NullString `db:"social_nets" json:"social_nets"`
	Wallets    sql.NullString `db:"wallets" json:"wallets"`
	Locations  sql.NullString `db:"locations" json:"locations"`
	Events     sql.NullString `db:"events" json:"events"`
	Notes      sql.NullString `db:"notes" json:"notes"`
}
