// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package contacts

import (
	"context"
)

type Querier interface {
	AddPeople(ctx context.Context, arg AddPeopleParams) (People, error)
	AddPeopleGroup(ctx context.Context, arg AddPeopleGroupParams) (People, error)
	DelPeople(ctx context.Context, name string) error
	//------------------------------
	// people
	//------------------------------
	GetPeople(ctx context.Context, name string) (People, error)
	//------------------------------
	// groups
	//------------------------------
	GetPeopleGroups(ctx context.Context, name string) (string, error)
	ListPeople(ctx context.Context) ([]People, error)
}

var _ Querier = (*Queries)(nil)
